import { useState } from 'react'
import { jsPDF } from 'jspdf'

const SERVICES = [
  { value: 'landing', label: 'Landing Page — K2,000' },
  { value: 'business', label: 'Business Website — K4,000' },
  { value: 'ecommerce', label: 'E-Commerce — K5,000' },
  { value: 'domain', label: 'Domain Name — K700' },
]

export default function ContractForm() {
  const [form, setForm] = useState({ name: '', email: '', service: '', signature: '' })
  const [downloading, setDownloading] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState(false)

  const update = (field, value) => setForm(prev => ({ ...prev, [field]: value }))

  const handleDownload = async () => {
    if (!form.name.trim()) return setError('Please enter your full name.')
    if (!form.service) return setError('Please select a service.')
    if (!form.signature.trim()) return setError('Please type your signature.')

    setError('')
    setDownloading(true)

    try {
      const doc = new jsPDF()
      const pageW = doc.internal.pageSize.getWidth()

      // Header bar
      doc.setFillColor(255, 107, 0)
      doc.rect(0, 0, pageW, 40, 'F')

      doc.setTextColor(255, 255, 255)
      doc.setFontSize(18)
      doc.setFont('helvetica', 'bold')
      doc.text('Website Development Service Agreement', 20, 22)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.text('Orange Core Web Dev Solutions', 20, 30)
      doc.setFontSize(9)
      doc.text(`Date: ${new Date().toLocaleDateString('en-GB')}`, pageW - 20, 30, { align: 'right' })

      // Body
      let y = 52
      doc.setTextColor(30, 30, 30)
      doc.setFontSize(11)

      const section = (title, body, yy) => {
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(12)
        doc.text(title, 20, yy)
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(10)
        const lines = doc.splitTextToSize(body, pageW - 40)
        doc.text(lines, 20, yy + 6)
        return yy + 8 + lines.length * 5
      }

      y = section(
        '1. Service Provider',
        'Orange Core Web Dev Solutions\n0203 Depot Road\nZambia'
      , y)

      y = section(
        '2. Client Details',
        `Name: ${form.name}\nEmail: ${form.email || 'N/A'}`
      , y)

      y = section(
        '3. Selected Service',
        `${SERVICES.find(s => s.value === form.service)?.label}`
      , y)

      y = section(
        '4. Project Timeline',
        'The project will be delivered within 5 business days of deposit confirmation.'
      , y)

      y = section(
        '5. Payment Terms',
        '50% deposit required before work begins.\nRemaining balance due before final handover.'
      , y)

      y = section(
        '6. Maintenance',
        'Client may select a maintenance plan after project delivery.'
      , y)

      // Signature
      y += 6
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(12)
      doc.text('7. Signatures', 20, y)
      y += 8

      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.text('Service Provider:', 20, y)
      y += 6
      doc.setFont('helvetica', 'italic')
      doc.setFontSize(14)
      doc.setTextColor(255, 107, 0)
      doc.text('Orange Core Web Dev Solutions', 20, y)
      y += 8

      doc.setFont('helvetica', 'normal')
      doc.setTextColor(30, 30, 30)
      doc.setFontSize(10)
      doc.text('Client:', 20, y)
      y += 6
      doc.setFont('helvetica', 'italic')
      doc.setFontSize(14)
      doc.setTextColor(255, 107, 0)
      doc.text(form.signature, 20, y)

      // Footer
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text('Generated by Orange Core Web Dev Solutions · Zambia', pageW / 2, 285, { align: 'center' })

      doc.save(`Orange-Core-Service-Agreement-${form.name.replace(/\s+/g, '_')}.pdf`)

      setSuccess(true)
      setTimeout(() => setSuccess(false), 3000)
    } catch (e) {
      setError('PDF generation failed. Please try again.')
    }
    setDownloading(false)
  }

  return (
    <section id="contract" className="py-24 px-6 bg-glossy-gray">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-12">
          <p className="section-label">Start Your Project</p>
          <h2 className="section-title">Download a Service Agreement</h2>
          <p className="section-subtitle max-w-xl mx-auto">
            Fill in the form below to generate a signed PDF service agreement instantly.
            No account required — download and take it from here.
          </p>
        </div>

        <div className="glass-card p-8 md:p-10">
          <div className="grid sm:grid-cols-2 gap-6 mb-6">
            <div>
              <label className="block text-sm font-bold text-dark mb-2">Your Full Name *</label>
              <input
                type="text"
                value={form.name}
                onChange={e => update('name', e.target.value)}
                placeholder="e.g. Chibesa Mwale"
                className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:border-orange focus:ring-2 focus:ring-orange/20 outline-none transition text-dark text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-bold text-dark mb-2">Email Address</label>
              <input
                type="email"
                value={form.email}
                onChange={e => update('email', e.target.value)}
                placeholder="client@example.com"
                className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:border-orange focus:ring-2 focus:ring-orange/20 outline-none transition text-dark text-sm"
              />
            </div>
          </div>

          <div className="mb-6">
            <label className="block text-sm font-bold text-dark mb-2">Select Service *</label>
            <select
              value={form.service}
              onChange={e => update('service', e.target.value)}
              className="w-full px-4 py-3 rounded-lg border border-gray-200 focus:border-orange focus:ring-2 focus:ring-orange/20 outline-none transition text-dark text-sm bg-white"
            >
              <option value="">— Choose a service —</option>
              {SERVICES.map(s => (
                <option key={s.value} value={s.value}>{s.label}</option>
              ))}
            </select>
          </div>

          <div className="mb-8">
            <label className="block text-sm font-bold text-dark mb-2">Type Signature *</label>
            <input
              type="text"
              value={form.signature}
              onChange={e => update('signature', e.target.value)}
              placeholder="Type your full name here to sign"
              style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic', fontSize: '1.2rem', color: '#FF6B00' }}
              className="w-full px-4 py-3 rounded-lg border border-gray-200 outline-none transition text-dark bg-transparent"
            />
            <p className="text-xs text-muted mt-1">Typing your name serves as a legally binding digital signature.</p>
          </div>

          {error && (
            <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700 flex items-center gap-2">
              <span>⚠️</span> {error}
            </div>
          )}

          {success && (
            <div className="mb-6 p-4 bg-green-50 border border-green-200 rounded-lg text-sm text-green-700 flex items-center gap-2">
              <span>✅</span> PDF downloaded! Check your downloads folder.
            </div>
          )}

          <button
            onClick={handleDownload}
            disabled={downloading}
            className="btn-primary text-base w-full justify-center py-4 disabled:opacity-60 disabled:cursor-not-allowed"
          >
            {downloading ? (
              <>⏳ Generating PDF…</>
            ) : (
              <>⬇️ Download Service Agreement (PDF)</>
            )}
          </button>
        </div>
      </div>
    </section>
  )
}